/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistaOficina;

import controlador.tda.lista.exception.TopeExeption;
import controladorOficina.OficinaController;
import javax.swing.JOptionPane;
import vistaOficina.Tablas.oficinaTabla;

/**
 *
 * @author jona
 */
public class Frm_TIckets extends javax.swing.JDialog {

    private OficinaController oc = new OficinaController();
    private oficinaTabla ot = new oficinaTabla();

    /**
     * Creates new form Frm_TIckets
     */
    private void agregar() {
        if (!oc.getCola2().getCola().estaLleno()) {
            try {
                oc.getTicket().setNombre(txtnombre.getText());
                oc.getTicket().setCodigo(oc.generarcodigo());
                limpiar();
            } catch (Exception e) {
            }
        }else {
        JOptionPane.showMessageDialog(null, "Ya no puede generar mas tickes", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
        

    }

    private void cargarTabla() {
        try {
            ot.setLista(oc.getCola2());
            tbltabla.setModel(ot);
            tbltabla.updateUI();
            oc.getCola2().queue(oc.getTicket());

        } catch (Exception e) {
        }

    }

    private void limpiar() {
        oc.setTicket(null);
        txtnombre.setText("");
        cargarTabla();
    }

    public Frm_TIckets(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltabla = new javax.swing.JTable();
        txtgenerar = new javax.swing.JButton();
        txtnombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Generador de ticket"));
        jPanel1.setLayout(null);

        jLabel1.setText("Nombre ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 40, 70, 20);

        tbltabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbltabla);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(42, 100, 460, 220);

        txtgenerar.setText("Generar");
        txtgenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgenerarActionPerformed(evt);
            }
        });
        jPanel1.add(txtgenerar);
        txtgenerar.setBounds(350, 40, 150, 23);
        jPanel1.add(txtnombre);
        txtnombre.setBounds(140, 40, 170, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 570, 360);

        setSize(new java.awt.Dimension(595, 404));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtgenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgenerarActionPerformed
        // TODO add your handling code here:
        agregar();
    }//GEN-LAST:event_txtgenerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_TIckets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_TIckets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_TIckets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_TIckets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Frm_TIckets dialog = new Frm_TIckets(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbltabla;
    private javax.swing.JButton txtgenerar;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
