/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistaComandos;

import controladorcomandos.ComandoController;
import vistaComandos.Tablas.comandosTabla;

/**
 *
 * @author jona
 */
public class Frm_Comandos extends javax.swing.JDialog {

    private ComandoController cc;
    private comandosTabla ct = new comandosTabla();

    /**
     * Creates new form Frm_Comandos
     */
    public Frm_Comandos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         //cargarTabla();
    }

    private void crear() {
        Integer tamanio = Integer.parseInt(cbxtamanio.getSelectedItem().toString());
        cc = new ComandoController(tamanio);
    }

    private void guardar() {
        if (cc.getCola().estaLleno()) {
            cc.extraer(0);
            cc.insertarc(txtcomando.getText());
        } else {
            cc.insertarc(txtcomando.getText());
        }
        cargarTabla();

        limpiar();
    }

    private void cargarTabla() {
        try {
            ct.setLista(cc.getCola());
            tbltabla.setModel(ct);
            tbltabla.updateUI();
        } catch (Exception e) {
        }

    }

    private void limpiar() {
        txtcomando.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtcomando = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltabla = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cbxtamanio = new javax.swing.JComboBox<>();
        bntSeleccionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Comados");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Comando "));
        jPanel1.setLayout(null);

        jLabel1.setText("Ingrese el comando:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 80, 140, 20);
        jPanel1.add(txtcomando);
        txtcomando.setBounds(180, 80, 110, 23);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar);
        btnGuardar.setBounds(334, 80, 110, 23);

        tbltabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbltabla);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 130, 452, 150);

        jLabel2.setText("Tamaño del historial:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 40, 170, 17);

        cbxtamanio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "6", "9", "12", "15", "18" }));
        jPanel1.add(cbxtamanio);
        cbxtamanio.setBounds(180, 40, 110, 23);

        bntSeleccionar.setText("Seleccionar");
        bntSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSeleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(bntSeleccionar);
        bntSeleccionar.setBounds(330, 40, 110, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 490, 300);

        setSize(new java.awt.Dimension(517, 353));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bntSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSeleccionarActionPerformed
        // TODO add your handling code here:
        crear();
    }//GEN-LAST:event_bntSeleccionarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        guardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Comandos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Comandos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Comandos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Comandos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Frm_Comandos dialog = new Frm_Comandos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSeleccionar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxtamanio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbltabla;
    private javax.swing.JTextField txtcomando;
    // End of variables declaration//GEN-END:variables
}
